version: '3.2'

services:
  app:
    image: yongshin/docker-node-app:latest
    deploy:
      replicas: 3
      labels:
        com.docker.ucp.mesh.http: "external_route=http://nodeapp.david.dtcntr.net,internal_port=4000"
    environment:
      - "MONGODB_SERVICE_SERVICE_HOST=nodeapp_db"
    ports:
      - 4000
    networks:
      - ucp-hrm
      - nodeapp-network

  db:
    image: clusterhq/mongodb
    deploy:
      replicas: 1
    networks:
      - nodeapp-network
    ports:
     - 27017:27017
    volumes:
     - db:/data/db

volumes:
  db:
    driver: local

networks:
  nodeapp-network:
    driver: overlay
  ucp-hrm:
    external: true
